# Generated by Django 3.1.6 on 2021-02-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailuser_validation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='next_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='next email address'),
        ),
    ]
