version: '3'
services:
  db:
    image: mdillon/postgis:11
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: django123
    expose:
      - '5432'
    ports:
      - '5434:5432'

